(in-package :yuka)

(defstruct frame
  (code nil)
  (klass nil)
  (locals nil :type simple-array)
  (operand-stack nil)
  (has-unhandled-exception nil))

(defun make-frame-from-code (code klass)
  (make-frame :code code
              :klass klass
	      :locals (make-array (code-attribute-max-locals code))
	      :operand-stack (make-stack (code-attribute-max-stack code))
              :has-unhandled-exception nil))

(defun monitor-exit ()
  (format t "(monitor-exit) not implemented!~%"))

(defun frame-run (self)
  (let* ((pc 0) (code (frame-code self))
         (bcode (code-attribute-code code)) 
         (len (length bcode))
         (cp (klass-constant-pool (frame-klass self)))
         (locals (frame-locals self))
         (operand-stack (frame-operand-stack self))
         (return-from-frame nil))
    (loop (when (or (>= pc len) return-from-frame)
            (return))
       (let ((opc (aref bcode pc)))
         (case (opcode-symbol opc)
           ((aaload)
            (aaload operand-stack))
           ((aastore)
            (aastore operand-stack))
           ((aconst_null)
            (stack-push operand-stack nil))
           ((aload)
            (aload locals operand-stack (opcode-operands opc)))
           ((aload_0)
            (aload locals operand-stack 0))
           ((aload_1)
            (aload locals operand-stack 1))
           ((aload_2)
            (aload locals operand-stack 2))
           ((aload_3)
            (aload locals operand-stack 3))
           ((anewarray)
            (anewarray operand-stack cp (opcode-operands opc)))
           ((areturn)
            (monitor-exit)
            (setf return-from-frame t))
           ((arraylength)
            (arraylength operand-stack))
           ((astore)
            (astore locals operand-stack (opcode-operands opc)))
           ((astore_0)
            (astore locals operand-stack 0))
           ((astore_1)
            (astore locals operand-stack 1))
           ((astore_2)
            (astore locals operand-stack 2))
           ((astore_3)
            (astore locals operand-stack 3))
           ((athrow)
            (setf pc (athrow operand-stack 
                             (code-attribute-exception-table code)
                             cp))                             
            (when (< pc 0)
              (monitor-exit)
              (setf (frame-has-unhandled-exception self) t)
              (setf return-from-frame t)))
           ((baload)
            (baload operand-stack))
           ((bastore)
            (bastore operand-stack))
           ((bipush)
            (stack-push operand-stack (opcode-operands opc)))
           ((caload)
            (caload operand-stack))
           ((castore)
            (castore operand-stack))
           ((checkcast)
            (checkcast operand-stack (opcode-operands opc) cp))
           ((d2f)
            (d2f operand-stack))
           ((d2i)
            (d2i operand-stack))
           ((istore_0)
            (istore locals operand-stack 0))
           ((istore_1)
            (istore locals operand-stack 1))
           ((istore_2)
            (istore locals operand-stack 2))
           ((istore_3)
            (istore locals operand-stack 3))
           ((return)
            (monitor-exit)
            (setf return-from-frame t)))
         (setf pc (1+ pc)))))
  self)

